name: Deploy to Minikube using GitHub Actions

on: [push]
  
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build Node.js Docker Image and deploy to minikube
    steps:
    - uses: actions/checkout@v2
    - name: Start Minikube
      run: minikube start --driver=docker

    - name: Wait for Minikube to be ready
      run: |
        for i in {1..30}; do
          minikube status | grep -q 'Running' && break
          sleep 5
        done
    - name: Check Minikube Status
      run: minikube status
    - name: Try the cluster !
      run: kubectl get pods -A
    - name: Build image
      run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build -f ./Dockerfile -t devopshint/node-app:latest .
          echo -n "verifying images:"
          docker images
    - name: Print Minikube Docker Env
      run: minikube -p minikube docker-env
    - name: Check Minikube logs if failure
      if: failure()
      run: cat /tmp/minikube_service_ba873920b9ac8d1e0c86efebfbdc1732e36079e5_0.log || echo "Log not found"
    - name: Deploy to minikube
      run:
        kubectl apply -f k8s-node-app.yaml
    - name: Test service URLs
      run: |
          minikube service list
          minikube service nodejs-app --url
